import ideathon from "./assets/ideathon.png";
import coding from "./assets/coding.png";
import blind from "./assets/blind.png";
import debug from "./assets/debugging.png";
import freefire from "./assets/freefire.png";
import bgmi from "./assets/bgmi.png";
import treasure from "./assets/treasure.png";
import minimiltia from "./assets/minimiltia.png";
import pcroomgames from "./assets/pcroomgames.png";
import pes from "./assets/pes.png";
import jamming from "./assets/jammingsession.png";
import reels from "./assets/reels.png";
import photography from "./assets/photography.png";

const styles = {
  paddingX: "sm:px-16 px-6",
  paddingY: "sm:py-16 py-6",
  padding: "sm:px-16 px-6 sm:py-16 py-10",

  heroHeadText:
    "font-black text-white lg:text-[80px] sm:text-[60px] xs:text-[50px] text-[40px] lg:leading-[98px] mt-2",
  heroSubText:
    "text-[#dfd9ff] font-medium lg:text-[30px] sm:text-[26px] xs:text-[20px] text-[16px] lg:leading-[40px]",

  sectionHeadText:
    " font-black md:text-[60px] sm:text-[50px] xs:text-[40px] text-[30px] text-rose-200",
  sectionSubText:
    "sm:text-[18px] text-[14px] text-secondary uppercase tracking-wider text-rose-200",
};

export const Data = [
  {
    event: "Treasure Hunt",
    desc: "Sharpen your skills, follow the clues, and uncover hidden surprises for a thrilling and rewarding adventure.",
    image: treasure,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
  {
    event: "Ideathon",
    desc: "Go on... Create, and pitch groundbreaking ideas that could shape the future of technology and beyond.",
    image: ideathon,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
  {
    event: "Debugging",
    desc: "Navigate through intricate code puzzles, spot errors, and emerge as the debugging champion. ",
    image: debug,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
  {
    event: "Blind Coding",
    desc: "Step into the coding unknown with our Blind Coding Competition! Trust your skills, rely on logic, and unveil your coding prowess.",
    image: blind,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
  {
    event: "Competative Coding",
    desc: "Prepare for the coding battleground in our Competitive Coding event! Challenge yourself against the clock and fellow participants. ",
    image: coding,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
  {
    event: "BGMI",
    desc: "Embark on an epic journey in our BGmi Gaming Competition! Battle it out, showcase your skills, and strive for victory in this intense esports showdown.",
    image: bgmi,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Online Event",
  },
  {
    event: "FreeFire",
    desc: "Gear up for intense gaming action in our Free Fire competition! Join the battle, showcase your skills, and emerge as the last one standing in this thrilling esports showdown.",
    image: freefire,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Online Event",
  },
  {
    event: "MiniMiltia",
    desc: "Gear up for intense gaming action in our Free Fire competition! Join the battle, showcase your skills, and emerge as the last one standing in this thrilling esports showdown.",
    image: minimiltia,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Online Event",
  },
  {
    event: "PC Room Games",
    desc: "Gear up for intense gaming action in our Free Fire competition! Join the battle, showcase your skills, and emerge as the last one standing in this thrilling esports showdown.",
    image: pcroomgames,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Online Event",
  },
  {
    event: "Jamming Session",
    desc: "Gear up for intense gaming action in our Free Fire competition! Join the battle, showcase your skills, and emerge as the last one standing in this thrilling esports showdown.",
    image: jamming,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
  {
    event: "PES",
    desc: "Gear up for intense gaming action in our Free Fire competition! Join the battle, showcase your skills, and emerge as the last one standing in this thrilling esports showdown.",
    image: pes,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Online Event",
  },
  {
    event: "Reels Competition",
    desc: "Gear up for intense gaming action in our Free Fire competition! Join the battle, showcase your skills, and emerge as the last one standing in this thrilling esports showdown.",
    image: reels,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
  {
    event: "Photography Competition",
    desc: "Gear up for intense gaming action in our Free Fire competition! Join the battle, showcase your skills, and emerge as the last one standing in this thrilling esports showdown.",
    image: photography,
    price: 2000,
    Rules: [
      "Teams must consist of a minimum of 3 members and a maximum of 6 members.",
      "All team members must be registered participants of the competition.",
      "Teams must register in advance to participate in the treasure hunt competition.",
      "Registration fees, if applicable, must be paid before the event.",
      "Each team will be assigned a unique team name and identification number.",
      "Teams must prominently display their identification number during the competition.",
      "The competition will begin at a designated starting point, announced at the event.",
      "Teams must gather at the starting point at the specified time.",
      "Clues and riddles will guide teams from one location to the next.",
      "Teams must solve each clue to determine the next location.",
      "Clues will be provided in written form or through a designated event app.",
      "Teams must adhere to the local laws and regulations during the competition.",
      "Respect private property and seek permission if required to enter premises.",
      "The competition will have a designated time limit.",
      "Teams must return to the final location within the specified time.",
      "Teams must not engage in any form of cheating or sabotage.",
      "Any team found violating fair play rules may be disqualified.",
      "Teams must prioritize their safety and the safety of others during the competition.",
      "Follow traffic rules and exercise caution in crowded areas.",
      "Teams may be disqualified for not following the rules, engaging in unsportsmanlike conduct, or violating safety guidelines.",
      "The decision of the event organizers is final and binding.",
      "Prizes will be awarded to the first, second, and third-place teams based on completion time and accuracy.",
      "Prizes may include certificates, medals, or other rewards.",
      "Event organizers reserve the right to modify rules, locations, or other aspects of the competition if necessary.",
      "Any unforeseen circumstances will be addressed at the discretion of the organizers.",
      "Teams are encouraged to provide feedback and suggestions for improvement after the event.",
      "Constructive criticism will be considered for future competitions.",
      "By participating in the treasure hunt competition, teams agree to abide by these rules and regulations. Event organizers reserve the right to disqualify any team that fails to comply with these rules or engages in behavior deemed inappropriate.",
    ],
    cordinators: [
      {name: 'Sreeganesh', number: '+91 1111111111'},
      {name: 'Vaishnav', number: '+91 1111111111'},
      {name: 'Ramduth', number: '+91 1111111111'}
    ],
    category: "Main Event",
  },
];

export { styles };
